### ISSUE TITLE
Add Paketo Slack link to issue template

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/.github#3]
## What happened?

Could we look into adding a slack link in our issues template? This could be a good way to point more users to the Paketo slack to ask questions, give feedback, etc.

The CNB project does something similar and it looks like:
![image](https://user-images.githubusercontent.com/37810054/106185299-a5c03280-6170-11eb-9253-5a3f1e72b40e.png)

**Comment by andymoe** [comment]
Looks like there is a new way (tm) to do issues templates that we have to move to before we can get something like described in the screenshot. More here... https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates - I don't think I can just do a PR unfortunately as it seems like it might be a settings.

**Comment by fg-j** [comment]
This is done! See https://github.com/paketo-buildpacks/go-build/issues/new/choose
