### ISSUE TITLE
Please add links to CLA text

### ISSUE THREAD

**Issue by kpfleming** [paketo-buildpacks/.github#8]
I'm trying to review contributions to this org's repositories on behalf of my employer, and in order to do that I need to have the CLA text reviewed and approved by our legal team.

Unfortunately the CONTRIBUTING.md in this repository doesn't include a link to the relevant CLAs, and that file does not appear in the other repos in the org so they don't have any contribution guidelines at all.

Thanks for your time, hopefully this is an easy issue to resolve :-)

**Comment by sophiewigmore** [comment]
Hey @kpfleming - we could use a bit of clarity on what the ask is here. Are you after the actual CLA documents, or just the [link to where to sign it](https://corporate.v1.easycla.lfx.linuxfoundation.org/)?

**Comment by kpfleming** [comment]
Ideally, both. Potential contributors (at least in our case) would like to be able to review the agreement they will be asked to sign (and the reviewers may not be able to review it in the CLA management tool, but must do it offline), and also potential contributors would like to be able to understand what the CLA management tool will require from them. For example, if the CLA management tool requires linking to a GitHub account, but the person signing the CLA is trying to do it on behalf of an organization, they can't link to their personal GitHub account.

**Comment by sophiewigmore** [comment]
@kpfleming Thanks for the extra info, I'm trying to get the official links from CFF. 

In the meantime to get unblocked, it's not ideal but you can view the CLA like this:
- go to https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/8943302/246858804/40/#/?version=1
- login with Github
- Click "Individual" and the CLA should come up.
I'm assuming you need the Corporate one, which doesn't show up there, but I will update you when I get the official link.

**Comment by sophiewigmore** [comment]
Yea, once I have everything together I will definitely update CONTRIBUTING.md with all of this information, good idea.

**Comment by sophiewigmore** [comment]
Here are the two official CFF CLAs:
[ccla.pdf](https://github.com/paketo-buildpacks/.github/files/6118298/ccla.pdf)
[icla.pdf](https://github.com/paketo-buildpacks/.github/files/6118299/icla.pdf)

They will also be accessible through our docs shortly.
